# Generated by Django 2.1 on 2018-08-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
